import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SECRET_KEY = os.environ.get("ARMPANEL_SECRET", "armpanel-secret-key-change-me")
DATABASE_PATH = os.path.join(BASE_DIR, "armpanel.db")


PANEL_HOST = "0.0.0.0"
PANEL_PORT = 1569
TTYD_PORT = 1570

GITHUB_REPO = "https://github.com/mustafacil38/armpanel"

DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"

# Default service definitions
# Her servis: name, icon, description, command_start, command_stop,
#             command_restart, process_name, default_port, config_files
DEFAULT_SERVICES = [
    {
        "name": "Nginx",
        "icon": "fa-solid fa-server",
        "description": "Web sunucusu (HTTP/HTTPS)",
        "command_start": "nginx",
        "command_stop": "nginx -s stop",
        "command_restart": "nginx -s reload",
        "process_name": "nginx",
        "default_port": 8080,
        "config_files": "/etc/nginx/nginx.conf,/etc/nginx/sites-available/default",
    },
    {
        "name": "ttyd",
        "icon": "fa-solid fa-terminal",
        "description": "Web tabanlı terminal",
        "command_start": f"/usr/local/bin/ttyd -p {TTYD_PORT} -W tmux new -A -s armpanel &",
        "command_stop": "pkill -f ttyd",
        "command_restart": f"pkill -f ttyd; sleep 1; /usr/local/bin/ttyd -p {TTYD_PORT} -W tmux new -A -s armpanel &",
        "process_name": "ttyd",
        "default_port": TTYD_PORT,
        "config_files": "",
    },
    {
        "name": "PHP-FPM",
        "icon": "fa-brands fa-php",
        "description": "PHP FastCGI işlem yöneticisi",
        "command_start": "php-fpm8.4",
        "command_stop": "pkill -f php-fpm",
        "command_restart": "pkill -f php-fpm; sleep 1; php-fpm8.4",
        "process_name": "php-fpm",
        "default_port": 9000,
        "config_files": "/etc/php/8.4/fpm/php.ini,/etc/php/8.4/fpm/pool.d/www.conf",
    },
    {
        "name": "File Browser",
        "icon": "fa-solid fa-folder-open",
        "description": "Web tabanlı dosya yöneticisi",
        "command_start": "filebrowser -d /etc/filebrowser/filebrowser.db -a 0.0.0.0 -p 8083 -r / &",
        "command_stop": "pkill -f filebrowser",
        "command_restart": "pkill -f filebrowser; sleep 1; filebrowser -d /etc/filebrowser/filebrowser.db -a 0.0.0.0 -p 8083 -r / &",
        "process_name": "filebrowser",
        "default_port": 8083,
        "config_files": "",
    },
    {
        "name": "AdGuard Home",
        "icon": "fa-solid fa-shield-halved",
        "description": "Reklam ve izleme engelleyici DNS sunucusu",
        "command_start": "/opt/adguardhome/AdGuardHome -c /opt/adguardhome/AdGuardHome.yaml -w /opt/adguardhome &",
        "command_stop": "pkill -f AdGuardHome",
        "command_restart": "pkill -f AdGuardHome; sleep 2; /opt/adguardhome/AdGuardHome -c /opt/adguardhome/AdGuardHome.yaml -w /opt/adguardhome &",
        "process_name": "AdGuardHome",
        "default_port": 3000,
        "config_files": "/opt/adguardhome/AdGuardHome.yaml",
    },
    {
        "name": "Nextcloud",
        "icon": "fa-solid fa-cloud",
        "description": "Kişisel bulut depolama platformu",
        "command_start": "nginx -s reload; php-fpm8.4",
        "command_stop": "pkill -f php-fpm",
        "command_restart": "pkill -f php-fpm; sleep 1; php-fpm8.4; nginx -s reload",
        "process_name": "php-fpm",
        "default_port": 8081,
        "config_files": "/var/www/nextcloud/config/config.php,/etc/nginx/sites-available/nextcloud",
    },
    {
        "name": "n8n",
        "icon": "fa-solid fa-diagram-project",
        "description": "İş akışı otomasyon platformu",
        "command_start": "n8n start --port=5678 &",
        "command_stop": "pkill -f 'n8n start'",
        "command_restart": "pkill -f 'n8n start'; sleep 2; n8n start --port=5678 &",
        "process_name": "n8n",
        "default_port": 5678,
        "config_files": "",
    },
    {
        "name": "Ghost",
        "icon": "fa-solid fa-ghost",
        "description": "Modern blog ve yayıncılık platformu",
        "command_start": "cd /var/www/ghost && npx ghost run --port=2368 &",
        "command_stop": "pkill -f 'ghost run'",
        "command_restart": "pkill -f 'ghost run'; sleep 2; cd /var/www/ghost && npx ghost run --port=2368 &",
        "process_name": "ghost",
        "default_port": 2368,
        "config_files": "/var/www/ghost/config.production.json",
    },
    {
        "name": "MariaDB",
        "icon": "fa-solid fa-database",
        "description": "İlişkisel veritabanı sunucusu",
        "command_start": "mysqld_safe --datadir=/var/lib/mysql &",
        "command_stop": "mysqladmin shutdown 2>/dev/null || pkill -f mysqld",
        "command_restart": "mysqladmin shutdown 2>/dev/null; sleep 2; mysqld_safe --datadir=/var/lib/mysql &",
        "process_name": "mysqld",
        "default_port": 3306,
        "config_files": "/etc/mysql/my.cnf,/etc/mysql/mariadb.conf.d/50-server.cnf",
    },
    {
        "name": "phpMyAdmin",
        "icon": "fa-solid fa-table",
        "description": "MySQL/MariaDB web yönetim arayüzü",
        "command_start": "nginx -s reload",
        "command_stop": "nginx -s stop",
        "command_restart": "nginx -s reload",
        "process_name": "nginx",
        "default_port": 8080,
        "config_files": "/var/www/html/phpmyadmin/config.inc.php",
    },
    {
        "name": "Jellyfin",
        "icon": "fa-solid fa-film",
        "description": "Medya sunucusu (film, müzik, dizi)",
        "command_start": "jellyfin --datadir /etc/jellyfin --cachedir /var/cache/jellyfin &",
        "command_stop": "pkill -f jellyfin",
        "command_restart": "pkill -f jellyfin; sleep 2; jellyfin --datadir /etc/jellyfin --cachedir /var/cache/jellyfin &",
        "process_name": "jellyfin",
        "default_port": 8096,
        "config_files": "/etc/jellyfin/network.xml,/etc/jellyfin/logging.default.json",
    },
    {
        "name": "Vaultwarden",
        "icon": "fa-solid fa-vault",
        "description": "Hafif Bitwarden şifre yöneticisi sunucusu",
        "command_start": "ROCKET_PORT=8085 /opt/vaultwarden/vaultwarden &",
        "command_stop": "pkill -f vaultwarden",
        "command_restart": "pkill -f vaultwarden; sleep 2; ROCKET_PORT=8085 /opt/vaultwarden/vaultwarden &",
        "process_name": "vaultwarden",
        "default_port": 8085,
        "config_files": "/opt/vaultwarden/.env,/opt/vaultwarden/config.json",
    },
    {
        "name": "Uptime Kuma",
        "icon": "fa-solid fa-heart-pulse",
        "description": "Sunucu ve site izleme aracı",
        "command_start": "node /opt/uptime-kuma/server/server.js &",
        "command_stop": "pkill -f 'uptime-kuma/server'",
        "command_restart": "pkill -f 'uptime-kuma/server'; sleep 2; node /opt/uptime-kuma/server/server.js &",
        "process_name": "node",
        "default_port": 3001,
        "config_files": "",
    },
    {
        "name": "Syncthing",
        "icon": "fa-solid fa-arrows-rotate",
        "description": "Cihazlar arası dosya senkronizasyonu",
        "command_start": "syncthing serve --no-browser --gui-address=0.0.0.0:8384 &",
        "command_stop": "syncthing cli shutdown 2>/dev/null || pkill -f syncthing",
        "command_restart": "syncthing cli shutdown 2>/dev/null; sleep 2; syncthing serve --no-browser --gui-address=0.0.0.0:8384 &",
        "process_name": "syncthing",
        "default_port": 8384,
        "config_files": "/root/.config/syncthing/config.xml",
    },
    {
        "name": "Samba",
        "icon": "fa-solid fa-share-nodes",
        "description": "Dosya paylaşım sunucusu (SMB/CIFS)",
        "command_start": "smbd -D; nmbd -D",
        "command_stop": "pkill -f smbd; pkill -f nmbd",
        "command_restart": "pkill -f smbd; pkill -f nmbd; sleep 1; smbd -D; nmbd -D",
        "process_name": "smbd",
        "default_port": 4455,
        "config_files": "/etc/samba/smb.conf",
    },
]
